# This workflow will trigger Datadog Synthetic tests within your Datadog organisation
# For more information on running Synthetic tests within your GitHub workflows see: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started:

# 1. Add your Datadog API (DD_API_KEY) and Application Key (DD_APP_KEY) as secrets to your GitHub repository. For more information, see: https://docs.datadoghq.com/account_management/api-app-keys/.
# 2. Start using the action within your workflow

name: Run Datadog Synthetic tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Run Synthetic tests within your GitHub workflow.
    # For additional configuration options visit the action within the marketplace: https://github.com/marketplace/actions/datadog-synthetics-ci
    - name: Run Datadog Synthetic tests
      uses: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb # v1.4.0
      with:
        api_key: ${{secrets.DD_API_KEY}}
        app_key: ${{secrets.DD_APP_KEY}}
        test_search_query: 'tag:e2e-tests' #Modify this tag to suit your tagging strategy


            - имя: Кэш
  использует: actions/cache@v4.2.0
  с:
    # Список файлов, каталогов и шаблонов подстановочных знаков для кэширования и восстановления
    путь:
    # Явный ключ для восстановления и сохранения кэша
    ключ:
    # Упорядоченная многострочная строка, перечисляющая ключи, соответствующие префиксу, которые используются для восстановления устаревшего кэша, если для ключа не произошло попадания в кэш. Обратите внимание, что `cache-hit` возвращает false в этом случае.
    восстановление-ключей: # необязательно
    # Размер фрагмента, используемый для разделения больших файлов во время загрузки, в байтах
    размер-куска-загрузки: # необязательно
    # Необязательное логическое значение, если включено, позволяет средам выполнения Windows сохранять или восстанавливать кэши, которые могут быть восстановлены или сохранены соответственно на других платформах.
    enableCrossOsArchive: # необязательно, по умолчанию false
    # Сбой рабочего процесса, если запись кэша не найдена
    fail-on-cache-miss: # необязательно, по умолчанию false
    # Проверить, существует ли запись кэша для заданных входных данных (ключ, restore-keys) без загрузки кэша
    только для поиска: # необязательно, по умолчанию false
    # Запустить шаг поста, чтобы сохранить кэш, даже если другой шаг до этого завершится неудачей
    save-always: # необязательно, по умолчанию false
          @MxNSTRixXx 
